route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 10m
  receiver: 'webhook'
receivers:
  - name: 'webhook'
    webhook_configs:
      - url: '{{ALERTMANAGER_WEBHOOK_URL}}'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']