global:
  scrape_interval: 2m
  scrape_timeout: 1m
  evaluation_interval: 30s # Evaluate rules every 30 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - {{PROMETHEUS_ALERTMANAGER_URL}}
rule_files:
  - /etc/prometheus/prometheus-alerts.yml

scrape_configs:
  - job_name: Confluent Cloud
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: {{CONFLUENT_CLOUD_API_KEY}}
      password: {{CONFLUENT_CLOUD_API_SECRET}}
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-q8kr6p
        - lkc-kj6xxv
        - lkc-37xxkw
      "resource.ksql.id":
        - lksqlc-nxx0od
        - lksqlc-pkyr65
        - lksqlc-rj88g9
      "resource.schema_registry.id":
        - lsrc-x1gxg
      "resource.connector.id":
        - lcc-mz99n1
        - lcc-pj28oo

