{
 "title": "Confluent Cloud Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, kafka_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Kafka Clusters",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (confluent_kafka_server_partition_count)"
    }
   ]
  },
  {
   "title": "Total Connectors",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_connect_sent_bytes)"
    }
   ]
  },
  {
   "title": "Total ksqlDB Clusters",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_streaming_unit_count)"
    }
   ]
  },
  {
   "title": "Total Schemas",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_schema_registry_schema_count",
     "legendFormat": "{{schema_registry_id}}"
    }
   ]
  },
  {
   "title": "Retained bytes ",
   "type": "stat",
   "description": "Basic clusters have a max retained bytes limit of 5 TB prior to replication. ccloud_metrics_retained_bytes is after replication thus needs to be divided by 3.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_retained_bytes{ kafka_id=~\"$cluster\"})/3",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Ingress",
   "type": "stat",
   "description": "The delta count of bytes of the customer's data received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.\nThe standard cluster has a max of 250 MBps.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_received_bytes{ kafka_id=~\"$cluster\"} / 60)",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Cluster Egress",
   "type": "stat",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.\nStandard cluster has a max of 750MBps.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_sent_bytes{ kafka_id=~\"$cluster\"} /60 )",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Count (rate)",
   "type": "stat",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.\nStandard cluster maxes out at  15000 requests per second.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_request_count{ kafka_id=~\"$cluster\"}/60)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Avg. Active connections",
   "type": "stat",
   "description": "The count of active authenticated connections.\nStandard clusters limit active connections to 1000.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Partition count ",
   "type": "timeseries",
   "description": "The sum of partitions in a cluster. \nStandard cluster max partitions limit is 4096.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"}",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Partition count change (delta)",
   "type": "timeseries",
   "description": "This single stat provides the absolute difference between the number of partitions are the beginning and end of the 5 minute period. This over simplifies the problem, so more conservative thresholds are put in place. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "abs(delta(confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"}[5m]))",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "description": "The delta count of successful authentications. Each sample is the number of successful authentications since the previous data point. The count sampled every 60 seconds.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "confluent_kafka_server_successful_authentication_count{}",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_server_request_count{kafka_id=~\"$cluster\"}",
     "legendFormat": "{{kafka_id}}-{{type}}"
    }
   ]
  },
  {
   "title": "Metrics Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"Confluent Cloud\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}