{
 "title": "Confluent Cloud Connectors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source_connector_id",
    "label": "Source Connector Id",
    "query": {
     "query": "label_values(confluent_kafka_connect_sent_bytes,connector_id)"
    }
   },
   {
    "name": "sink_connector_id",
    "label": "Sink Connector Id",
    "query": {
     "query": "label_values(confluent_kafka_connect_received_bytes,connector_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect Sent Records",
   "type": "timeseries",
   "description": "The delta count of total number of records sent from the transformations and written to Kafka for the source connector. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_records{connector_id=~\"$source_connector_id\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Connector Received bytes",
   "type": "timeseries",
   "description": "The delta count of total bytes received by the sink connector. Each sample is the number of bytes received since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_bytes{connector_id=~\"$sink_connector_id\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Dead Letter Queue bytes",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_dead_letter_queue_records{connector_id=~\"$sink_connector_id|$source_connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Connector Sent bytes",
   "type": "timeseries",
   "description": "The delta count of total bytes sent from the transformations and written to Kafka for the source connector. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_bytes{connector_id=~\"$source_connector_id\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  },
  {
   "title": "Connector Received records",
   "type": "timeseries",
   "description": "The delta count of total number of records received by the sink connector. Each sample is the number of records received since the previous  data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_records{connector_id=~\"$sink_connector_id\"}",
     "legendFormat": "{{connector_id}} -- {{connector_id}}"
    }
   ]
  }
 ]
}