{
 "title": "Confluent Cloud ksqlDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ksql_id",
    "label": "ksqlDB Id",
    "query": {
     "query": "label_values(confluent_kafka_ksql_streaming_unit_count,ksql_id)"
    }
   },
   {
    "name": "query_id",
    "label": "Query Id",
    "query": {
     "query": "label_values(confluent_kafka_ksql_query_saturation,query_id)"
    }
   },
   {
    "name": "ksql_node_id",
    "label": "ksqlDB Node Id",
    "query": {
     "query": "label_values(confluent_kafka_ksql_task_stored_bytes,ksql_node_id)"
    }
   },
   {
    "name": "kafka_id",
    "query": {
     "query": "label_values(confluent_kafka_server_consumer_lag_offsets,kafka_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes,topic)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(confluent_kafka_server_consumer_lag_offsets,consumer_group_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ksqlDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ksqlDB Streaming Unit Count",
   "type": "stat",
   "description": "The count of Confluent Streaming Units (CSUs) for this KSQL instance. The count is sampled every 60 seconds. The implicit time aggregation for this metric is MAX.\n\n# TYPE confluent_kafka_ksql_streaming_unit_count gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_streaming_unit_count",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  {
   "title": "ksqlDB application count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_streaming_unit_count)"
    }
   ]
  },
  {
   "title": "Total Storage Utilization",
   "type": "timeseries",
   "description": "The total storage utilization for a given ksqlDB application. Storage utilization is a metric that measures the % of available storage that ksqlDB has used to store state for stateful queries like aggregations and joins. If this value reaches 100% (1.0) ksqlDB will not be able to continue to process records because it does not have available storage space to maintain state.\n\nTYPE confluent_kafka_ksql_task_stored_bytes gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_storage_utilization{ksql_id=~\"$ksql_id\"}",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  {
   "title": "ksqlDB Query Saturation",
   "type": "timeseries",
   "description": "The maximum saturation for a given ksqlDB query across all nodes. Returns a value between 0 and 1, a value close to 1 indicates that ksqlDB query processing is bottlenecked on available resources.\n\nQuery saturation measures the percentage of time a query-processing thread spends processing records, for example serializing/deserializing, evaluating expressions, and reading/writing state for aggregations and joins. When a query processing thread is not doing work, it’s waiting for new records to process, so if a query-processing thread is almost always busy, it likely can’t keep up with its source topic partitions. \n\nTYPE confluent_kafka_ksql_query_saturation gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_query_saturation{ksql_id=~\"$ksql_id\", query_id=~\"$query_id\"}",
     "legendFormat": "{{ksql_id}}|{{query_id}}"
    }
   ]
  },
  {
   "title": "ksqlDB Task Stored Bytes",
   "type": "timeseries",
   "description": "The size of a given task's state stores in bytes.\n\nTYPE confluent_kafka_ksql_task_stored_bytes gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, confluent_kafka_ksql_task_stored_bytes{ksql_id=~\"$ksql_id\", query_id=~\"$query_id\", ksql_node_id=~\"$ksql_node_id\"})",
     "legendFormat": "{{ksql_id}}|{{query_id}}|{{ksql_node_id}}|{{task_id}}"
    }
   ]
  },
  { "title": "Consumptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "description": "The lag between a group member's committed offset and the partition's high watermark.\n\nConsumer group lag measures the difference between the current processing offset and the latest offset for each source topic partition a query consumes. While this value may occasionally spike, consumer lag that’s consistently growing indicates the ksqlDB may not be able to keep up with records as they’re being appended to the topics that a query consumes from.\n\nTYPE confluent_kafka_server_consumer_lag_offsets gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, max by (consumer_group_id) (confluent_kafka_server_consumer_lag_offsets{kafka_id=~\"$kafka_id\", topic=~\"$topic\", consumer_group_id=~\"$group\"}))",
     "legendFormat": "{{consumer_group_id}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topic retained bytes",
   "type": "timeseries",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_retained_bytes{topic=~\"$topic\", kafka_id=~\"$kafka_id\"})",
     "legendFormat": "{{kafka_id}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Received Bytes",
   "type": "timeseries",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_bytes{topic=~\"$topic\", kafka_id=~\"$kafka_id\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Received Record",
   "type": "timeseries",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_records{topic=~\"$topic\", kafka_id=~\"$kafka_id\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "timeseries",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_bytes{topic=~\"$topic\", kafka_id=~\"$kafka_id\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent Records",
   "type": "timeseries",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_records{topic=~\"$topic\", kafka_id=~\"$kafka_id\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Confluent Cloud ksqlDB",
   "type": "text",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "# ksqlDB CSU\n\nA Confluent Streaming Unit is an abstract unit that represents the linearity of performance. For example, if a workload gets a certain level of throughput with 4 CSUs, you can expect about three times the throughput with 12 CSUs.\n\n- 1 CSU is the minimum.\n- 28 CSUs is the maximum.\n- Cluster sizes can be 1, 2, 4, 8, 12, 16, 20, 24, or 28 CSUs.\n- Clusters with 1 or 2 CSUs can be scaled up to 4. For clusters with 4 CSUs or more, you can scale up to 28 CSUs in 4-CSU increments.\n- Clusters with 8 or more CSUs are configured automatically for [high availability](https://docs.confluent.io/cloud/current/ksqldb/overview.html#ksqldb-high-availability).\n- High availability cannot be enabled for clusters with less than 8 CSUs.\n\n# ksqlDB Storages\nYou get 125 GB of storage space with each CSU. For 8 CSUs and higher, clusters are configured with [high availability](https://docs.confluent.io/cloud/current/ksqldb/overview.html#ksqldb-high-availability) automatically, and ksqlDB maintains replicas of your data that use half of the available storage. For 4 CSUs and 8 CSUs, you get 500 GB of user-available storage, so to expand storage past 500 GB, you must expand to at least 12 CSUs.\n\n\n|Number of CSUs | Storage | User-available storage |\n|----|----|----|\n1 | 125 GB | 125 GB |\n2 | 250 GB | 250 GB |\n4 | 500 GB | 500 GB |\n8 | 1000 GB | 500 GB* |\n12-28 | 1500 GB | 750 GB* |\n\n# ksqlDB Monitoring\n\nKey Items:\n- Processing Errors\n- Query Restarts\n- Storage Utilization\n- Consumer Group Lag\n- Query Saturation"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  }
 ]
}