{
 "title": "Confluent Cloud Topic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, kafka_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topic retained bytes",
   "type": "timeseries",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_retained_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{kafka_id}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Topic received bytes",
   "type": "timeseries",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic received record",
   "type": "timeseries",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_records{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "timeseries",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_bytes{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic sent records",
   "type": "timeseries",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_records{topic=~\"$topic\", kafka_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  }
 ]
}